Add Chinese translation
Sukigu/search-by-image-on-google pull request #7
Opened 2019-03-30 13:33 UTC by gospahdu

2019-04-03 10:54 UTC, Sukigu requested changes
Hi, and thanks for your contribution! 🙂 I would like to ask you to please change the directory name from `zh-CN` to `zh_CN`, as specified in Mozilla's [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Providing_localized_strings_in__locales).

2019-04-04 11:28 UTC, gospahdu commented
Hello,
I have changed the directory name,please recheck it

2019-04-04 15:54 UTC, Sukigu approved these changes

2019-04-04 15:57 UTC, Sukigu commented
Thank you! Your translation will be included in the next version.

2019-04-04 15:59 UTC, merged